apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: ubuntu-2204-vm
  name: ubuntu-2204-vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: ubuntu-2204-vm
    spec:
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: os
            - disk:
                bus: virtio
              name: cloudinitdisk
        resources:
          requests:
            memory: 512Mi
      volumes:
        - containerDisk:
            image: quay.io/containerdisks/ubuntu:22.04
          name: os
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              password: spud101!
              chpasswd: { expire: False }
          name: cloudinitdisk
